version: '3.8'

services:

  api:
    build:
      context: app
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/todo_back_end/infra/entrypoint.sh']
    volumes:
      - ../app:/usr/src/todo_back_end/app
    ports:
      - "5004:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
    depends_on:
      - api-db

  api-db:
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres